"""Exports the heap contents Carbon's GB audio thread found in its two AudioOut buffers, from an opencarbon Ryujinx
audio trace, as carbon-pc/src/gb/AudioHeapCapture.inc.

usage: export_startup_buffers.py <run dir> <session,slot>... [-o carbon-pc/src/gb/AudioHeapCapture.inc]

Each <session,slot> is a GB audio session (as listed by analyze.py) and 0 for buffer A or 1 for buffer B; capture
indices follow the order given. Only non-zero byte runs are emitted.
"""
import argparse, os, re

HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('run')
    ap.add_argument('picks', nargs='+')
    ap.add_argument('-o', '--out', default=os.path.join(HERE, '..', '..', 'carbon-pc', 'src', 'gb', 'AudioHeapCapture.inc'))
    args = ap.parse_args()
    log = open(os.path.join(args.run, 'events.log'), encoding='utf-8-sig').read()

    pool = bytearray()
    runs = []      # (capture, offset, length, pool offset)
    comments = []
    for index, pick in enumerate(args.picks):
        session, slot = (int(x) for x in pick.split(','))
        m = re.search(rf'session {session} guest buffer #{slot} tag \w+ ptr (0x\w+) size (\d+) file offset (\d+) (peak .*?) head', log)
        if not m:
            raise SystemExit(f'no guest buffer #{slot} in session {session}')
        size, offset = int(m[2]), int(m[3])
        data = open(os.path.join(args.run, f's{session}_guest.pcm'), 'rb').read()[offset:offset + size]
        if size != 0x2000:
            raise SystemExit(f'session {session} buffer #{slot} is {size} bytes, expected 0x2000')
        comments.append(f'// {index}: session {session} buffer {"AB"[slot]} @ guest {m[1]}, {m[4]}')
        k = 0
        while k < len(data):
            if data[k] == 0:
                k += 1
                continue
            j = k
            while j < len(data) and (data[j] != 0 or any(data[j:j + 8])):
                j += 1
            runs.append((index, k, j - k, len(pool)))
            pool += data[k:j]
            k = j

    run_name = os.path.basename(os.path.normpath(args.run))
    with open(args.out, 'w', newline='\n') as f:
        f.write(f'// Generated by tools/ryujinx_trace/export_startup_buffers.py from testresults/ryujinx_audio/{run_name}.\n')
        f.write('// What Carbon\'s GB audio thread found in its AudioOut buffers (never cleared) on Ryujinx 1.1.1403.\n')
        f.write('\n'.join(comments) + '\n')
        f.write(f'constexpr int kHeapCaptureCount = {len(args.picks)};\n')
        f.write('constexpr HeapCaptureRun kHeapCaptureRuns[] = {\n')
        for index, offset, length, pool_offset in runs:
            f.write(f'    {{{index}, 0x{offset:04x}, 0x{length:04x}, 0x{pool_offset:05x}}},\n')
        f.write('};\n')
        f.write('constexpr unsigned char kHeapCaptureBytes[] = {\n')
        for i in range(0, len(pool), 24):
            f.write('    ' + ', '.join(f'0x{b:02x}' for b in pool[i:i + 24]) + ',\n')
        f.write('};\n')
    print(f'{args.out}: {len(args.picks)} captures, {len(runs)} runs, {len(pool)} bytes')


if __name__ == '__main__':
    main()
